name: Tests Contract Simple RS
on: push
jobs:
  workflows:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Install and test modules
        run: |
          cd ./contract-simple-rs
          cargo test
